<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<select>
	<option>学院</option>
	<option>专业</option>
	<option>班级</option>
	<option>学号</option>
	<option>姓名</option>
	<option>性别</option>
	<option>生源地省</option>
	<option>生源地市</option>
	<option>生源地区</option>
	<option>学历</option>
	<option>毕业时间</option>
	<option>工作省份</option>
	<option>工作市</option>
	<option>工作地区</option>
	<option>工作单位</option>
	<option>职务</option>
	<option>职称</option>
	<option>行业</option>
	<option>联系电话</option>
	<option>固定电话</option>
	<option>邮箱</option>
	<option>QQ号</option>
	<option>通讯地址</option>
	<option>邮编</option>
	<option>备注</option>
	<option>所属校友总会</option>
	<option>校友总会职务</option>
	<option>所属校友分会</option>
	<option>校友分会职务</option>
</select>
<select>
	<option>等于</option>
	<option>不等于</option>
</select>
<input>
<span id="del" class="glyphicon glyphicon-remove" title="删除本条件"></span>